### ISSUE TITLE
Improve the code

### ISSUE THREAD

**Issue by sarabenchinoun** [sarabenchinoun/horiseon-code-refactor#5]
### Tasks:

- [x] Fix all links, so they function correctly.
- [x] Consolidate and organise CSS selectors and properties to follow the semantic structure.
- [x] Use comments to properly explain the code in the CSS file.
